name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'duyluonganh/kat-download-file'
          path: 'dev_repo'
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '7.8.1'
          projectPath: 'dev_repo'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/New Test Suite" -apiKey=${{ secrets.SECRET_KEY }} --config -webui.autoUpdateDrivers=true'
