name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Checkout dev repo
        uses: actions/checkout@v2
        with:
          repository: 'duyluonganh/kat-download-file' #https://github.com/duyluonganh/kat-download-file
          path: 'dev_repo'
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '7.8.1'
          projectPath: '${{ github.workspace }}/dev_repo'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/New Test Suite" -apiKey=${{ secrets.SECRET_KEY }}'
